//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test133.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Var3Entities : DbContext
    {
        public Var3Entities()
            : base("name=Var3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Избранные_товары> Избранные_товары { get; set; }
        public virtual DbSet<Категории> Категории { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Состав_заказа> Состав_заказа { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
    }
}
