//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test133.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Избранные_товары
    {
        public int Id_Избранного_товара { get; set; }
        public Nullable<int> Клиент { get; set; }
        public Nullable<int> Товар { get; set; }
    
        public virtual Клиент Клиент1 { get; set; }
        public virtual Товар Товар1 { get; set; }
    }
}
