//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test133.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Состав_заказа
    {
        public int Id_Состав_Заказа { get; set; }
        public Nullable<int> Заказ { get; set; }
        public Nullable<int> Товар { get; set; }
    
        public virtual Заказ Заказ1 { get; set; }
        public virtual Товар Товар1 { get; set; }
    }
}
